
- name: Unarchive a tomcat tar from tomcat website
  unarchive:
    src: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
    dest: /etc/
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
   - tar-copy

- name: create a soft link to th tomcat folder
  file:
    src: /etc/apache-tomcat-8.5.60
    dest: /etc/tomcat
    owner: root
    group: root
    state: link
  tags:
          - softlink

- name: Copy file with owner and permissions
  copy:
    src: files/tomcat-users.xml
    dest: /etc/tomcat/conf/tomcat-users.xml
    owner: root
    group: root
    mode: '0644'
